version: "3.8"
services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "https://pagamento.resolvenergiasolar.com"
    