FROM node:20

# Instalação das dependências necessárias
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++

# Instalação do Husky (opcional)
RUN npm install -g husky

# Copia os arquivos do projeto e instala as dependências
WORKDIR /app
COPY package.json package-lock.json ./

RUN npm install --production --legacy-peer-deps

# Copia o restante dos arquivos do projeto
COPY . .

# Criação do .env com as variáveis injetadas no build
ARG GENERATE_SOURCEMAP
ARG NEXT_PUBLIC_API_BASE_CLICKSIGN_TEMPLATE_ID
ARG NEXT_PUBLIC_API_BASE_CLICKSIGN_TEMPLATE_PRE_ID
ARG NEXT_PUBLIC_CLICKSIGN_TOKEN
ARG NEXT_PUBLIC_API_BASE_CLICKSIGN_URL
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_CONTENT_TYPE_LEAD_ID
ARG NEXT_PUBLIC_CONTENT_TYPE_PROJECT_ID
ARG NEXT_PUBLIC_SERVICE_INSPECTION_ID
ARG NEXT_PUBLIC_SUPABASE_KEY
ARG NEXT_PUBLIC_CONTENT_TYPE_SALE_ID
ARG NEXT_PUBLIC_SUPABASE_URL

RUN echo "GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP" >> .env && \
    echo "NEXT_PUBLIC_API_BASE_CLICKSIGN_TEMPLATE_ID=$NEXT_PUBLIC_API_BASE_CLICKSIGN_TEMPLATE_ID" >> .env && \
    echo "NEXT_PUBLIC_API_BASE_CLICKSIGN_TEMPLATE_PRE_ID=$NEXT_PUBLIC_API_BASE_CLICKSIGN_TEMPLATE_PRE_ID" >> .env && \
    echo "NEXT_PUBLIC_CLICKSIGN_TOKEN=$NEXT_PUBLIC_CLICKSIGN_TOKEN" >> .env && \
    echo "NEXT_PUBLIC_API_BASE_CLICKSIGN_URL=$NEXT_PUBLIC_API_BASE_CLICKSIGN_URL" >> .env && \
    echo "NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL" >> .env && \
    echo "NEXT_PUBLIC_CONTENT_TYPE_LEAD_ID=$NEXT_PUBLIC_CONTENT_TYPE_LEAD_ID" >> .env && \
    echo "NEXT_PUBLIC_CONTENT_TYPE_PROJECT_ID=$NEXT_PUBLIC_CONTENT_TYPE_PROJECT_ID" >> .env && \
    echo "NEXT_PUBLIC_SERVICE_INSPECTION_ID=$NEXT_PUBLIC_SERVICE_INSPECTION_ID" >> .env && \
    echo "NEXT_PUBLIC_SUPABASE_KEY=$NEXT_PUBLIC_SUPABASE_KEY" >> .env && \
    echo "NEXT_PUBLIC_CONTENT_TYPE_SALE_ID=$NEXT_PUBLIC_CONTENT_TYPE_SALE_ID" >> .env && \
    echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL" >> .env

# Realiza o build da aplicação
RUN npm run build

# Inicia o servidor Next.js em produção
CMD ["npm", "start"]
