import {
  IconHome,
  IconPoint,
  IconApps,
  IconClipboard,
  IconFileDescription,
  IconBorderAll,
  IconZoomCode,
  IconRotate,
  IconUserPlus,
  IconLogin,
  IconAlertCircle,
  IconSettings,
} from '@tabler/icons-react';
import { uniqueId } from 'lodash';

const Menuitems = [
 /*  {
    id: uniqueId(),
    title: 'Dashboard',
    icon: IconHome,
    href: '/dashboards/',
    children: [
      {
        id: uniqueId(),
        title: 'Modern',
        icon: IconPoint,
        href: '/',
        chip: 'New',
        chipColor: 'secondary',
      },
      {
        id: uniqueId(),
        title: 'eCommerce',
        icon: IconPoint,
        href: '/dashboards/ecommerce',
      },
    ],
  }, */
  {
    id: uniqueId(),
    title: 'Aplicativos',
    icon: IconApps,
    href: '/apps/',
    children: [
      {
        id: uniqueId(),
        title: 'Contatos',
        icon: IconPoint,
        href: '/apps/contacts',
      },
      {
        id: uniqueId(),
        title: 'Chats',
        icon: IconPoint,
        href: '/apps/chats',
      },
      {
        id: uniqueId(),
        title: 'Notas',
        icon: IconPoint,
        href: '/apps/notes',
      },
      {
        id: uniqueId(),
        title: 'Calendário',
        icon: IconPoint,
        href: '/apps/calendar',
      },
      {
        id: uniqueId(),
        title: 'Notificações',
        icon: IconPoint,
        href: '/apps/notification',
      },
      {
        id: uniqueId(),
        title: 'Tickets',
        icon: IconPoint,
        href: '/apps/tickets',
      },
      {
        id: uniqueId(),
        title: 'Perfil do Usuário',
        icon: IconPoint,
        href: '/user-profile',
        children: [
          {
            id: uniqueId(),
            title: 'Perfil',
            icon: IconPoint,
            href: '/apps/user-profile/profile',
          },
          {
            id: uniqueId(),
            title: 'Seguidores',
            icon: IconPoint,
            href: '/apps/user-profile/followers',
          },
          {
            id: uniqueId(),
            title: 'Colegas',
            icon: IconPoint,
            href: '/apps/user-profile/friends',
          },
          {
            id: uniqueId(),
            title: 'Galeria',
            icon: IconPoint,
            href: '/apps/user-profile/gallery',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Ecommerce',
        icon: IconPoint,
        href: '/apps/ecommerce/',
        children: [
          {
            id: uniqueId(),
            title: 'Loja',
            icon: IconPoint,
            href: '/apps/ecommerce/shop',
          },
          {
            id: uniqueId(),
            title: 'Detalhe',
            icon: IconPoint,
            href: '/apps/ecommerce/detail/1',
          },
          {
            id: uniqueId(),
            title: 'Lista',
            icon: IconPoint,
            href: '/apps/ecommerce/list',
          },
          {
            id: uniqueId(),
            title: 'Checkout',
            icon: IconPoint,
            href: '/apps/ecommerce/checkout',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Quadros',
        icon: IconPoint,
        href: '/apps/boards/crm',
      },
      {
        id: uniqueId(),
        title: 'Fatura',
        icon: IconPoint,
        href: '/apps/invoice/list',
        children: [
          {
            id: uniqueId(),
            title: 'Lista',
            icon: IconPoint,
            href: '/apps/invoice/list',
          },
          {
            id: uniqueId(),
            title: 'Detalhes',
            icon: IconPoint,
            href: '/apps/invoice/detail/PineappleInc',
          },
          {
            id: uniqueId(),
            title: 'Criar',
            icon: IconPoint,
            href: '/apps/invoice/create',
          },
          {
            id: uniqueId(),
            title: 'Editar',
            icon: IconPoint,
            href: '/apps/invoice/edit/PineappleInc',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Blog',
        icon: IconPoint,
        href: '/apps/blog/',
        children: [
          {
            id: uniqueId(),
            title: 'Postagens',
            icon: IconPoint,
            href: '/apps/blog/post',
          },
          {
            id: uniqueId(),
            title: 'Detalhe',
            icon: IconPoint,
            href: '/apps/blog/detail/streaming-video-way-before-it-was-cool-go-dark-tomorrow',
          },
        ],
      },
    ],
  },

  {
    id: uniqueId(),
    title: 'Páginas',
    icon: IconClipboard,
    href: '/ui-components/',
    children: [
      {
        id: uniqueId(),
        title: 'Acesso Baseado em Função',
        icon: IconPoint,
        href: '/theme-pages/casl',
      },
      {
        id: uniqueId(),
        title: 'Árvore de Visualização',
        icon: IconPoint,
        href: '/theme-pages/treeview',
      },
      {
        id: uniqueId(),
        title: 'Preços',
        icon: IconPoint,
        href: '/theme-pages/pricing',
      },
      {
        id: uniqueId(),
        title: 'Configuração da Conta',
        icon: IconPoint,
        href: '/theme-pages/account-settings',
      },
      {
        id: uniqueId(),
        title: 'FAQ',
        icon: IconPoint,
        href: '/theme-pages/faq',
      },
      {
        id: uniqueId(),
        title: 'Widgets',
        icon: IconPoint,
        href: '/widgets/cards',
        children: [
          {
            id: uniqueId(),
            title: 'Cartões',
            icon: IconPoint,
            href: '/widgets/cards',
          },
          {
            id: uniqueId(),
            title: 'Banners',
            icon: IconPoint,
            href: '/widgets/banners',
          },
          {
            id: uniqueId(),
            title: 'Gráficos',
            icon: IconPoint,
            href: '/widgets/charts',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Ui',
        icon: IconPoint,
        href: '/ui-components/alert',
        children: [
          {
            id: uniqueId(),
            title: 'Alerta',
            icon: IconPoint,
            href: '/ui-components/alert',
          },
          {
            id: uniqueId(),
            title: 'Acordeão',
            icon: IconPoint,
            href: '/ui-components/accordion',
          },
          {
            id: uniqueId(),
            title: 'Avatar',
            icon: IconPoint,
            href: '/ui-components/avatar',
          },
          {
            id: uniqueId(),
            title: 'Chip',
            icon: IconPoint,
            href: '/ui-components/chip',
          },
          {
            id: uniqueId(),
            title: 'Diálogo',
            icon: IconPoint,
            href: '/ui-components/dialog',
          },
          {
            id: uniqueId(),
            title: 'Lista',
            icon: IconPoint,
            href: '/ui-components/list',
          },
          {
            id: uniqueId(),
            title: 'Popover',
            icon: IconPoint,
            href: '/ui-components/popover',
          },
          {
            id: uniqueId(),
            title: 'Avaliação',
            icon: IconPoint,
            href: '/ui-components/rating',
          },
          {
            id: uniqueId(),
            title: 'Abas',
            icon: IconPoint,
            href: '/ui-components/tabs',
          },
          {
            id: uniqueId(),
            title: 'Tooltip',
            icon: IconPoint,
            href: '/ui-components/tooltip',
          },
          {
            id: uniqueId(),
            title: 'Lista de Transferência',
            icon: IconPoint,
            href: '/ui-components/transfer-list',
          },
          {
            id: uniqueId(),
            title: 'Tipografia',
            icon: IconPoint,
            href: '/ui-components/typography',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Gráficos',
        icon: IconPoint,
        href: '/charts/',
        children: [
          {
            id: uniqueId(),
            title: 'Linha',
            icon: IconPoint,
            href: '/charts/line',
          },
          {
            id: uniqueId(),
            title: 'Gradiente',
            icon: IconPoint,
            href: '/charts/gradient',
          },
          {
            id: uniqueId(),
            title: 'Área',
            icon: IconPoint,
            href: '/charts/area',
          },
          {
            id: uniqueId(),
            title: 'Candlestick',
            icon: IconPoint,
            href: '/charts/candlestick',
          },
          {
            id: uniqueId(),
            title: 'Coluna',
            icon: IconPoint,
            href: '/charts/column',
          },
          {
            id: uniqueId(),
            title: 'Rosca & Torta',
            icon: IconPoint,
            href: '/charts/doughnut',
          },
          {
            id: uniqueId(),
            title: 'RadialBar & Radar',
            icon: IconPoint,
            href: '/charts/radialbar',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Autenticação',
        icon: IconPoint,
        href: '/400',
        children: [
          {
            id: uniqueId(),
            title: 'Erro',
            icon: IconAlertCircle,
            href: '/400',
          },
          {
            id: uniqueId(),
            title: 'Manutenção',
            icon: IconSettings,
            href: '/auth/maintenance',
          },
          {
            id: uniqueId(),
            title: 'Login',
            icon: IconLogin,
            href: '/auth/auth1/login',
            children: [
              {
                id: uniqueId(),
                title: 'Login Lateral',
                icon: IconPoint,
                href: '/auth/auth1/login',
              },
              {
                id: uniqueId(),
                title: 'Login em Caixa',
                icon: IconPoint,
                href: '/auth/auth2/login',
              },
            ],
          },
          {
            id: uniqueId(),
            title: 'Registrar',
            icon: IconUserPlus,
            href: '/auth/auth1/register',
            children: [
              {
                id: uniqueId(),
                title: 'Registro Lateral',
                icon: IconPoint,
                href: '/auth/auth1/register',
              },
              {
                id: uniqueId(),
                title: 'Registro em Caixa',
                icon: IconPoint,
                href: '/auth/auth2/register',
              },
            ],
          },
          {
            id: uniqueId(),
            title: 'Esqueceu a Senha',
            icon: IconRotate,
            href: '/auth/auth1/forgot-password',
            children: [
              {
                id: uniqueId(),
                title: 'Esqueceu a Senha Lateral',
                icon: IconPoint,
                href: '/auth/auth1/forgot-password',
              },
              {
                id: uniqueId(),
                title: 'Esqueceu a Senha em Caixa',
                icon: IconPoint,
                href: '/auth/auth2/forgot-password',
              },
            ],
          },
          {
            id: uniqueId(),
            title: 'Dois Passos',
            icon: IconZoomCode,
            href: '/auth/auth1/two-steps',
            children: [
              {
                id: uniqueId(),
                title: 'Dois Passos Lateral',
                icon: IconPoint,
                href: '/auth/auth1/two-steps',
              },
              {
                id: uniqueId(),
                title: 'Dois Passos em Caixa',
                icon: IconPoint,
                href: '/auth/auth2/two-steps',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Formulários',
    icon: IconFileDescription,
    href: '/forms/form-elements/autocomplete',
    children: [
      {
        id: uniqueId(),
        title: 'Elementos do Formulário',
        icon: IconPoint,
        href: '/forms/form-elements/autocomplete',
        children: [
          {
            id: uniqueId(),
            title: 'Autocompletar',
            icon: IconPoint,
            href: '/forms/form-elements/autocomplete',
          },
          {
            id: uniqueId(),
            title: 'Botão',
            icon: IconPoint,
            href: '/forms/form-elements/button',
          },
          {
            id: uniqueId(),
            title: 'Rádio',
            icon: IconPoint,
            href: '/forms/form-elements/radio',
          },
          {
            id: uniqueId(),
            title: 'Data e Hora',
            icon: IconPoint,
            href: '/forms/form-elements/date-time',
          },
          {
            id: uniqueId(),
            title: 'Deslizante',
            icon: IconPoint,
            href: '/forms/form-elements/slider',
          },
          {
            id: uniqueId(),
            title: 'Interruptor',
            icon: IconPoint,
            href: '/forms/form-elements/switch',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Layout do Formulário',
        icon: IconPoint,
        href: '/forms/form-layout',
      },
      {
        id: uniqueId(),
        title: 'Formulário Horizontal',
        icon: IconPoint,
        href: '/forms/form-horizontal',
      },
      {
        id: uniqueId(),
        title: 'Formulário Vertical',
        icon: IconPoint,
        href: '/forms/form-vertical',
      },
      {
        id: uniqueId(),
        title: 'Formulário Personalizado',
        icon: IconPoint,
        href: '/forms/form-custom',
      },
      {
        id: uniqueId(),
        title: 'Assistente de Formulário',
        icon: IconPoint,
        href: '/forms/form-wizard',
      },
      {
        id: uniqueId(),
        title: 'Validação de Formulário',
        icon: IconPoint,
        href: '/forms/form-validation',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Tabelas',
    icon: IconBorderAll,
    href: '/tables/',
    children: [
      {
        id: uniqueId(),
        title: 'Básico',
        icon: IconPoint,
        href: '/tables/basic',
      },
      {
        id: uniqueId(),
        title: 'Colapsável',
        icon: IconPoint,
        href: '/tables/collapsible',
      },
      {
        id: uniqueId(),
        title: 'Aprimorado',
        icon: IconPoint,
        href: '/tables/enhanced',
      },
      {
        id: uniqueId(),
        title: 'Cabeçalho Fixo',
        icon: IconPoint,
        href: '/tables/fixed-header',
      },
      {
        id: uniqueId(),
        title: 'Paginação',
        icon: IconPoint,
        href: '/tables/pagination',
      },
      {
        id: uniqueId(),
        title: 'Pesquisa',
        icon: IconPoint,
        href: '/tables/search',
      },
      {
        id: uniqueId(),
        title: 'Tabelas React',
        icon: IconPoint,
        href: '/tables/',
        children: [
          {
            id: uniqueId(),
            title: 'Básico',
            icon: IconPoint,
            href: '/react-tables/basic',
          },
          {
            id: uniqueId(),
            title: 'Denso',
            icon: IconPoint,
            href: '/react-tables/dense',
          },
          {
            id: uniqueId(),
            title: 'Filtro',
            icon: IconPoint,
            href: '/react-tables/filter',
          },
          {
            id: uniqueId(),
            title: 'Seleção de Linha',
            icon: IconPoint,
            href: '/react-tables/row-selection',
          },
          {
            id: uniqueId(),
            title: 'Paginação',
            icon: IconPoint,
            href: '/react-tables/pagination',
          },
          {
            id: uniqueId(),
            title: 'Ordenação',
            icon: IconPoint,
            href: '/react-tables/sorting',
          },
          {
            id: uniqueId(),
            title: 'Visibilidade da Coluna',
            icon: IconPoint,
            href: '/react-tables/column-visiblity',
          },
          {
            id: uniqueId(),
            title: 'Arrastar e Soltar',
            icon: IconPoint,
            href: '/react-tables/drag-n-drop',
          },
          {
            id: uniqueId(),
            title: 'Editável',
            icon: IconPoint,
            href: '/react-tables/editable',
          },
          {
            id: uniqueId(),
            title: 'Vazio',
            icon: IconPoint,
            href: '/react-tables/empty',
          },
          {
            id: uniqueId(),
            title: 'Expandir',
            icon: IconPoint,
            href: '/react-tables/expanding',
          },
          {
            id: uniqueId(),
            title: 'Fixo',
            icon: IconPoint,
            href: '/react-tables/sticky',
          },
        ],
      },
    ],
  },
];
export default Menuitems;
