import { uniqueId } from 'lodash';

import {

  IconBoxMultiple,
  IconCalendar,
  IconClockQuestion,
  IconCurrencyDollar,
  IconFileDescription,
  IconStar,
  IconLayoutKanban,
  IconChartLine,
  IconBox,
  IconShoppingCart,
  IconUser,
  IconUsers,
  IconBuilding,
  IconVector,
  IconUserScan,
  IconTools,
  IconHomeQuestion,
  IconMailFast,
  IconUserDollar
} from '@tabler/icons-react';

const Menuitems = [
  {
    navlabel: true,
    subheader: 'Home',
  },
  {
    id: uniqueId(),
    title: 'Quadros',
    icon: IconLayoutKanban,
    href: '/apps/boards/crm',
    chip: 'Novo',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Agendamentos',
    icon: IconCalendar,
    href: '/apps/inspections/schedule',
    permissions: ['inspections.view_schedule'],
  },
  {
    id: uniqueId(),
    title: 'Vendas',
    icon: IconShoppingCart,
    href: '/apps/commercial/sale',
    permissions: ['resolve_crm.view_sale'],
  },
  {
    id: uniqueId(),
    title: 'Pagamentos',
    icon: IconCurrencyDollar,
    href: '/apps/invoice',
    permissions: ['financial.view_payment'],
  },
  {
    id: uniqueId(),
    title: 'Comissionamento',
    icon: IconUserDollar,
    href: '/apps/commission',
    permissions: ['financial.view_payment'],
  },
  {
    id: uniqueId(),
    title: 'Projetos',
    icon: IconTools,
    href: '/apps/project',
    permissions: ['resolve_crm.view_project'],
  },
  {
    id: uniqueId(),
    title: 'Solicitações Conce.',
    icon: IconMailFast,
    href: '/apps/request',
    permissions: ['resolve_crm.view_project'],
  },
  {
    id: uniqueId(),
    title: 'Campanhas',
    icon: IconStar,
    href: '/apps/campaign',
    permissions: ['resolve_crm.view_marketingcampaign'],
    title: 'Categorias',
    icon: IconBox,
    href: '/apps/inspections/category',
  },
  {
    id: uniqueId(),
    title: 'Prazos',
    icon: IconClockQuestion,
    href: '/apps/inspections/deadline',
    permissions: ['inspections.view_deadline'],
  },
  {
    id: uniqueId(),
    title: 'Serviços',
    icon: IconBoxMultiple,
    href: '/apps/inspections/service-catalog',
    permissions: ['inspections.view_service'],
  },
  {
    id: uniqueId(),
    title: 'Formulários',
    icon: IconFileDescription,
    href: '/apps/inspections/form-builder',
    permissions: ['inspections.view_forms'],
  },
  {
    id: uniqueId(),
    title: 'Tipos de Telhado',
    icon: IconHomeQuestion,
    href: '/apps/inspections/roof-type',
    permissions: ['inspections.view_rooftype'],
  },
  {
    id: uniqueId(),
    title: 'Usuários',
    icon: IconUser,
    href: '/apps/users',
    permissions: ['accounts.view_user'],
  },
  {
    id: uniqueId(),
    title: 'Squads',
    icon: IconUsers,
    href: '/apps/squad',
    permissions: ['accounts.view_squad'],
  },
  {
    id: uniqueId(),
    title: 'Franquias',
    icon: IconBuilding,
    href: '/apps/branch',
    permissions: ['accounts.view_branch'],
  },
  {
    id: uniqueId(),
    title: 'Departamentos',
    icon: IconVector,
    href: '/apps/department',
    permissions: ['accounts.view_department'],
  },
  {
    id: uniqueId(),
    title: 'Cargos',
    icon: IconUserScan,
    href: '/apps/roles',
    permissions: ['accounts.view_role'],
  },
  {
    id: uniqueId(),
    title: 'TimeLine',
    icon: IconChartLine,
    href: '/apps/timeline',
    permissions: ['accounts.view_role'],
  },
  {
    id: uniqueId(),
    title: 'Contas a Pagar e Receber',
    icon: IconCurrencyDollar,
    href: '/apps/financial-record',
    permissions: ['financial.view_financialrecord'],
  }
];

export default Menuitems;
