import {
  IconUserBolt,
  IconTruckDelivery,
  IconSolarPanel2,
  IconUserSearch,
  IconSettings,
  IconShoppingCart,
  IconUser,
  IconUserPin,
  IconBuildingBank,
  IconTools,
  IconUsers,
  IconBuilding,
  IconVector,
  IconUserScan,
  IconFileDescription,
  IconCurrencyDollar,
  IconTrendingUp,
  IconMapRoute,
  IconCalendarStar,
  IconCash,
  IconReportMoney,
  IconPigMoney,
  IconPaperclip,
  IconFileArrowRight,
  IconHeadset,
} from '@tabler/icons-react';
import { uniqueId } from 'lodash';

const Menuitems = [
  {
    id: uniqueId(),
    title: 'Comercial',
    icon: IconTrendingUp,
    href: '/apps/commercial/sale',
    permissions: ['resolve_crm.view_sale', 'resolve_crm.view_lead', 'core.view_board'],
    children: [
      {
        id: uniqueId(),
        title: 'Vendas',
        icon: IconShoppingCart,
        href: '/apps/commercial/sale',
        permissions: ['resolve_crm.view_sale'],
      },
      {
        id: uniqueId(),
        title: 'Agendamentos',
        icon: IconUserPin,
        href: '/apps/commercial/schedules',
        permissions: ['resolve_crm.view_lead'],
      },
      {
        id: uniqueId(),
        title: 'Rotas de Agentes',
        icon: IconMapRoute,
        href: '/apps/schedules/agents-routes',
        permissions: ['field_services.view_all_schedule'],
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Financeiro',
    icon: IconCurrencyDollar,
    href: '/apps/invoice',
    permissions: ['financial.view_financialrecord'],
    children: [
      {
        id: uniqueId(),
        title: 'Faturamento',
        icon: IconCash,
        href: '/apps/invoice',
        permissions: ['resolve_crm.can_manage_journey'],
      },
      {
        id: uniqueId(),
        title: 'Solic. de Pagamento',
        icon: IconReportMoney,
        href: '/apps/financial-record',
        permissions: ['financial.view_financialrecord'],
      },
      {
        id: uniqueId(),
        title: 'Anexos',
        icon: IconPaperclip,
        href: '/apps/financial-record/attachments',
        permissions: ['financial.view_financialrecord_attachment'],
      },
      {
        id: uniqueId(),
        title: 'Solicitações Sicoob',
        icon: IconPigMoney,
        permissions: ['contracts.view_sicoobrequest'],
        href: '/apps/funding-request/sicoob',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Serviços de Campo',
    icon: IconUserPin,
    href: '/apps/schedules',
    permissions: ['field_services.can_see_admin_schedules'],
    children: [
      {
        id: uniqueId(),
        title: 'Agendamentos',
        icon: IconCalendarStar,
        href: '/apps/schedules',
        permissions: ['field_services.can_see_admin_schedules'],
      },
      {
        id: uniqueId(),
        title: 'Rotas de Agentes',
        icon: IconMapRoute,
        href: '/apps/schedules/agents-routes',
        permissions: ['field_services.can_see_admin_schedules'],
      },
      {
        id: uniqueId(),
        title: 'Calendário',
        icon: IconCalendarStar,
        href: '/apps/calendar',
        permissions: ['field_services.can_see_admin_schedules'],
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Jornada do cliente',
    icon: IconMapRoute,
    href: '/apps/project',
    permissions: ['resolve_crm.can_view_journey'],
  },
  {
    id: uniqueId(),
    title: 'Relacionamento',
    icon: IconUsers,
    permissions: ['resolve_crm.can_manage_journey'],
    children: [
      {
        id: uniqueId(),
        title: 'Agendamentos',
        icon: IconUserPin,
        href: '/apps/relationship/schedules',
        permissions: ['field_services.view_schedule'],
      },
      {
        id: uniqueId(),
        title: 'Tickets',
        icon: IconHeadset,
        href: '/apps/customer-service',
        permissions: ['field_services.view_schedule'],
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Gestão Operacional',
    icon: IconUserBolt,
    permissions: ['resolve_crm.can_manage_journey'],
    children: [
      {
        id: uniqueId(),
        title: 'Vistoria',
        icon: IconUserSearch,
        href: '/apps/inspections',
        permissions: ['resolve_crm.can_manage_journey'],
      },
      {
        id: uniqueId(),
        title: 'Logística',
        icon: IconTruckDelivery,
        href: '/apps/logistics',
        permissions: ['resolve_crm.can_manage_journey'],
      },
      {
        id: uniqueId(),
        title: 'Instalação',
        icon: IconSolarPanel2,
        href: '/apps/installation',
        permissions: ['resolve_crm.can_manage_journey'],
      },
      {
        id: uniqueId(),
        title: 'Obras',
        icon: IconBuilding,
        href: '/apps/constructions',
        permissions: ['engineering.view_civilconstruction'],
      },
      {
        id: uniqueId(),
        title: 'Homologação',
        icon: IconFileArrowRight,
        href: '/apps/request',
        permissions: ['resolve_crm.can_manage_journey'],
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Config. Sistema',
    icon: IconSettings,
    permissions: [
      'accounts.view_squad',
      'accounts.view_branch',
      'accounts.view_department',
      'accounts.view_role',
      'core.view_documenttype',
    ],
    children: [
      {
        id: uniqueId(),
        title: 'Usuários',
        icon: IconUser,
        href: '/apps/users',
        permissions: ['accounts.view_user'],
      },
      {
        id: uniqueId(),
        title: 'Squads',
        icon: IconUsers,
        href: '/apps/squad',
        permissions: ['accounts.view_squad'],
      },
      {
        id: uniqueId(),
        title: 'Franquias',
        icon: IconBuilding,
        href: '/apps/branch',
        permissions: ['accounts.view_branch'],
      },
      {
        id: uniqueId(),
        title: 'Departamentos',
        icon: IconVector,
        href: '/apps/department',
        permissions: ['accounts.view_department'],
      },
      {
        id: uniqueId(),
        title: 'Cargos',
        icon: IconUserScan,
        href: '/apps/roles',
        permissions: ['accounts.view_role'],
      },
      {
        id: uniqueId(),
        title: 'Tipos de Documentos',
        icon: IconFileDescription,
        href: '/apps/document-types',
        permissions: ['core.view_documenttype'],
      },
    ],
  },
];
export default Menuitems;
