name: CI/CD Pipeline for resolve-erp-frontend

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: "resourceresolve.azurecr.io/resolve-erp-frontend"
  AKS_CLUSTER_NAME: "Resolve-AKS-Web"
  AKS_RESOURCE_GROUP: "Resolve"
  NAMESPACE: "resolve-frontend-erp"
  DEPLOYMENT_NAME: "resolve-erp-frontend"

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    environment: resolve

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      run: echo "${{ vars.AZURE_ACR_PASSWORD }}" | docker login resourceresolve.azurecr.io -u "${{ vars.AZURE_ACR_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image with Cache
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        tags: |
          $DOCKER_IMAGE:${{ github.sha }}
        cache-from: type=registry,ref=$DOCKER_IMAGE:cache
        cache-to: type=registry,mode=max,ref=$DOCKER_IMAGE:cache
        push: true

    - name: Log in to Azure
      run: az login --service-principal -u "${{ vars.AZURE_CLIENT_ID }}" -p "${{ vars.AZURE_CLIENT_SECRET }}" --tenant "${{ vars.AZURE_TENANT_ID }}"

    - name: Configure Access to AKS
      run: |
        az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing

    - name: Update Deployment on AKS
      run: |
        kubectl set image deployment/$DEPLOYMENT_NAME resolve-erp-frontend=$DOCKER_IMAGE:${{ github.sha }} -n $NAMESPACE
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE
