name: CI/CD Pipeline for resolve-erp-frontend

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: "resourceresolve.azurecr.io/resolve-erp-frontend"
  AKS_CLUSTER_NAME: "Resolve-AKS-Web"
  AKS_RESOURCE_GROUP: "Resolve"
  NAMESPACE: "resolve-frontend-erp"
  DEPLOYMENT_NAME: "resolve-erp-frontend"

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login resourceresolve.azurecr.io -u "${{ secrets.AZURE_ACR_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t $DOCKER_IMAGE:${{ github.sha }} .
        docker push $DOCKER_IMAGE:${{ github.sha }}

  deploy:
    name: Deploy to AKS
    needs: build
    runs-on: ubuntu-24.04

    steps:
    - name: Log in to Azure
      run: az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"

    - name: Set up kubectl
      run: az aks install-cli

    - name: Configure Access to AKS
      run: |
        az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing

    - name: Update Deployment on AKS
      run: |
        kubectl set image deployment/$DEPLOYMENT_NAME resolve-erp-frontend=$DOCKER_IMAGE:${{ github.sha }} -n $NAMESPACE
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE
